<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnCookies</name>
   <tag></tag>
   <elementGuidId>fd730692-b5d2-41d3-a26b-69ec1fcae67a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.cc-btn</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
