<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>optLogin</name>
   <tag></tag>
   <elementGuidId>f3ef6bf2-4072-4fb8-841a-ae77290d5f72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[href='https://www.phptravels.net/login']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
